const {boot}=require('./qa_mock.js');const {api}=boot();const {S,CAMP,GUIDE,DECG,$}=api;
const html=require('fs').readFileSync(require('path').join(__dirname,'..','index.html'),'utf8');
let fails=0;const log=(ok,m)=>{if(!ok)fails++;console.log((ok?'  ✓ ':'  ✗ ')+m);};
console.log('Content integrity');
const keys=Object.keys(GUIDE);
const badRel=[];keys.forEach(k=>(GUIDE[k].rel||[]).forEach(r=>{if(!GUIDE[r])badRel.push(k+'→'+r);}));log(!badRel.length,`${keys.length} guide cards; every "Related" link resolves ${badRel.join(',')}`);
const miss=keys.filter(k=>GUIDE[k].kind!=='Apparatus'&&!(GUIDE[k].what&&GUIDE[k].when&&GUIDE[k].wrong&&GUIDE[k].tip));log(!miss.length,'Every control/gauge/concept card has all four sections '+miss.join(','));
const dg=[...new Set([...html.matchAll(/data-g="([^"$]+)"/g)].map(m=>m[1]))].concat(['discharge','deck']);const badG=dg.filter(g=>!GUIDE[g]);log(!badG.length,`Every tappable panel element (${dg.length} types) has a guide card ${badG.join(',')}`);
const decTags=[];CAMP.forEach(c=>c.missions.forEach(m=>m.steps.forEach(s=>{if(s.dec)decTags.push(s.dec.tag);})));const badDec=decTags.filter(t=>!DECG[t]||!GUIDE[DECG[t]]);log(!badDec.length,`All ${decTags.length} decision cards link to a guide card ${badDec.join(',')}`);
const reasons=[...html.matchAll(/ding\(\d+,\s*(?:c\.depth\?)?'([^']+)'/g)].map(m=>m[1]).concat([...html.matchAll(/ding\(\d+,`([^`$]+)/g)].map(m=>m[1]));
const unmapped=[...new Set(reasons)].filter(r=>!/^Decision — $/.test(r)&&!api.incidentKey(r));log(!unmapped.length,`${new Set(reasons).size} distinct penalty messages each link to a lesson`+(unmapped.length?': UNMAPPED → '+unmapped.join(' | '):''));
['102','fdny10','lafd209','dump'].forEach(r=>log(!!GUIDE['rig-'+r],'Apparatus card exists: '+GUIDE['rig-'+r]?.name));
console.log('\nMission briefings (controls shown before each mission)');
let emptyBrief=0;CAMP.forEach(c=>c.missions.forEach(m=>{const ks=api.missionControls(c,m);if(!ks.length)emptyBrief++;console.log('   '+(c.name.slice(0,22)+' · '+m.title).slice(0,58).padEnd(59)+ks.map(k=>GUIDE[k].name.split(' (')[0].split(' &')[0]).join(', '));}));
log(!emptyBrief,'Every mission briefing lists at least one control');
console.log('\nTier rules');
api.setTier(0);api.loadCampaign(0);log(!$('briefov')._cls.has('hidden')&&!S.running,'Guided: briefing opens and the clock waits');
$('brief-go').onclick();log(S.running,'Guided: "Start mission" starts the clock');
$('b-guide').onclick();log(api.LEARN()&&!S.running,'Panel guide enters learn mode and pauses the clock');
const sc=S.score;api.openCard('primer');log(S.score===sc&&!$('guideov')._cls.has('hidden'),'Guided: looking up a card is free');
$('g-close').onclick();$('lb-done').onclick();log(!api.LEARN()&&S.running,'Done: leaves learn mode and resumes the clock');
api.setTier(1);api.loadCampaign(0);$('brief-go').onclick();const s1=S.score;$('b-guide').onclick();api.openCard('primer');api.openCard('primer');api.openCard('ttp');
log(S.score===s1-4,`Recall: −2 per new card, repeat looks free (score ${s1} → ${S.score})`);$('lb-done').onclick();
api.loadCampaign(0);const s2=S.score;api.openCard('primer',true);log(S.score===s2,'Recall: studying from the briefing is free');$('brief-go').onclick();
api.setTier(2);api.loadCampaign(0);log($('briefov')._cls.has('hidden')&&S.running,'Chaos: no briefing — straight into the mission');
$('b-guide').onclick();log(!api.LEARN(),'Chaos: Panel guide is locked mid-mission');
$('b-menu').onclick();$('b-gindex').onclick();log(!$('guideov')._cls.has('hidden'),'Chaos: full guide still browsable from the menu');
console.log('\nPenalty → lesson');
api.setTier(0);api.loadCampaign(0);$('brief-go').onclick();$('s-pump').onclick();for(let i=0;i<20;i++)api.tick(0.25);api.setValve('front','snap');
log(S.incidents.some(x=>/Water hammer/.test(x)),'Snapping a valve open is penalized as water hammer');
S.mission=S.mission;const last=api.S;api.loadCampaign(0);$('brief-go').onclick();
console.log('\n'+(fails?fails+' CHECK(S) FAILED':'ALL GUIDE CHECKS PASSED'));
