// "Let them make the mistake, then teach it" (Max, October 7, 2026): a button for a wrong action never refuses.
// The action happens (or is attempted for real), a small deduction lands, and the feedback line says why.
// Prerequisites that can't physically happen (a bag that isn't set up, a wound not yet found, a medic not yet there)
// and decision points stay as they are; the KEEP list below names them, so a new refusal can't slip in unnoticed.
const fs=require('fs'),path=require('path');const {boot}=require('./pc_mock.js');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const answer=api=>{const D=api.DECO();if(!D)return;const i=D.opts.findIndex(o=>o.r==='good');api.$('dec-opts').onclick({target:{closest:()=>({dataset:{i:String(i)}})}});api.$('dec-go').onclick();};
function open(call,force,tier=0){global.window.FORCE_V=force?{[call]:force}:null;const {api}=boot();api.setTier(tier);api.loadCall(call);global.window.FORCE_V=null;api.$('brief-go').onclick();for(let i=0;i<6;i++){answer(api);api.tick(.25);}answer(api);return api;}
const KEEP=[/Motion detected/,/Protocol guide is locked/,/Back plate goes in/,/Did you check her pelvis/,/How many are you sending/,/BVM|Bag-mask first/,/Breaths? (aren't|isn't) going in|No chest rise/,/Check him first/,/Hold on — is there a DNR/,/He gags on it/,/fights the bag/,/coughing on it/,/Rolling him back/,/Syringe and filter needle first/,/ampule is expired|brownish/,/Find it first|Find out what's hurt|Get in with her first/,/won't keep the mask on/,/No placenta yet/];
module.exports=function(report){
  const T=(name,fn)=>{let r;try{r=fn();}catch(e){r={ok:false,d:e.message};}report('teach',name,!!r.ok,r.d||'');};
  // every remaining refusal is a prerequisite, a decision point, the medic's own device, or the consequence of an attempt that really happened
  {const left=[...html.matchAll(/radio\('[^']*',([^;]{0,160}?),'bad'\);return;/g)].map(m=>m[1].replace(/\\/g,'')).filter(t=>!KEEP.some(k=>k.test(t)));
   report('teach','no button refuses a wrong action: every remaining refusal is a prerequisite, a decision point or the medic\'s own call',left.length===0,left.slice(0,3).join(' | ')||'all accounted for');}
  T('chest pain: laid flat with a normal pressure, costs 3, he sits back up, and the line says why',()=>{const a=open('cp',{key:'classic'});const S=a.S();S.h.abc=true;const s=S.score;a.$('k-flat').onclick();return {ok:s-S.score===3&&!S.h.flat&&/makes breathing harder/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('chest pain: a pulse check off schedule stops compressions and costs 2',()=>{const a=open('cp',{key:'vf'});const S=a.S();Object.assign(S.h,{abc:true,arr:true,arrRt:S.rt,arrT:S.t,arrChecked:true,cpr:true,cprStartRt:S.rt});const s=S.score;a.$('k-chk').onclick();return {ok:s-S.score===2&&!S.h.cpr&&S.h.act&&/off schedule/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('pediatric: the bag on a child breathing for himself goes on, he fights it, costs 3',()=>{const a=open('pd',{kind:'asthma',inh:'own',tire:false});const S=a.S();S.p.listen=true;const s=S.score,ag=S.p.agit;a.$('p-bvm').onclick();return {ok:s-S.score===3&&!S.p.bvm&&S.p.agit>ag&&/breathing for himself/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('pediatric: his brother\'s inhaler, tapped anyway, goes in, costs 10, and the debrief names it',()=>{const a=open('pd',{kind:'asthma',inh:'sibling'});const S=a.S();a.setM(a.M());S.mission=1;const s=S.score;a.$('p-puff').onclick();for(let i=0;i<40;i++)a.tick(.25);return {ok:s-S.score===10&&S.p.trapUsed&&S.p.puffs===1,d:`−${s-S.score}`};});
  T('overdose: an OPA in a patient who gags is tried, he gags, costs 5',()=>{const a=open('od',{L:1});const S=a.S();S.o.checked=true;S.o.gcs=12;const s=S.score;a.$('o-opa').onclick();return {ok:s-S.score===5&&!S.o.opa&&/gag reflex/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('overdose: rolled onto his side while breathing under 10, costs 5, rolled back to the bag',()=>{const a=open('od',{L:1});const S=a.S();S.o.checked=true;S.o.rr=6;S.o.withdrawal=false;const s=S.score;a.$('o-recov').onclick();return {ok:s-S.score===5&&!S.o.recov&&/still needs breaths/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('diabetic: oral glucose to a man who can\'t swallow is tried, he coughs, costs 10 once, no sugar given',()=>{const a=open('dm',{low:true,pill:false});const S=a.S();Object.assign(S.d,{keys:true,abc:true,sw:false});const s=S.score,n=S.d.doseT.length;a.$('d-tube').onclick();a.$('d-tube').onclick();return {ok:s-S.score===10&&S.d.doseT.length===n&&/into his lungs/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('childbirth: fundal massage before the placenta costs 3 once; looking before the history costs 2 and the look still happens',()=>{const a=open('cb',{});const S=a.S();const s=S.score;a.$('c-look').onclick();const look=!!(S.c.act&&S.c.act.k==='look');a.setM(a.M());S.mission=3;S.c.placenta=false;S.c.massage=false;a.$('c-massage').onclick();a.$('c-massage').onclick();return {ok:s-S.score===5&&look&&/before the history/.test(S.incidents.join(' '))&&/before the placenta/.test(S.incidents.join(' ')),d:`−${s-S.score}, look ${look}`};});
  T('childbirth: the newborn out of the restraint in the ambulance costs 5, and she goes back in',()=>{const a=open('cb',{vig:true});const S=a.S();a.setM(a.M());S.mission=4;Object.assign(S.c,{born:true,vigorous:true,sts:false});const s=S.score;a.$('b-sts').onclick();return {ok:s-S.score===5&&!S.c.sts&&/restraint/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('stroke: oxygen on a normal SpO₂ goes on, costs 3, and says it is not indicated',()=>{const a=open('st',{lvo:false});const S=a.S();S.s.abc=true;S.s.spo2=97;const s=S.score;a.$('s-o2').onclick();return {ok:s-S.score===3&&S.s.o2on&&/Not indicated with SpO₂ at or above 94 per protocol\. Extra oxygen doesn't help a stroke/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('cardiac arrest: compressions during analysis cost 5 and the analysis starts over',()=>{const a=open('arrest',{open:'cpr',outcome:'rosc',shock:true});const S=a.S();S.checked=true;S.arrest=true;S.aed.pads=true;S.cpr.on=false;S.aed.state='analyzing';S.aed.stT=3;const s=S.score;a.$('a-cpr').onclick();return {ok:s-S.score===5&&S.aed.state==='analyzing'&&S.aed.stT===0&&!S.cpr.on,d:`−${s-S.score}`};});
  T('cardiac arrest: breaths before the 30 stop compressions, cost 3, and CPR resumes after them',()=>{const a=open('arrest',{open:'cpr',outcome:'rosc',shock:true});const S=a.S();S.checked=true;S.arrest=true;S.air.bvm=true;S.cpr.on=true;S.cpr.who='You';S.vent.waiting=false;S.act=null;const s=S.score;a.$('a-breaths').onclick();const stopped=!S.cpr.on;for(let i=0;i<12;i++)a.tick(.25);return {ok:s-S.score>=3&&stopped&&S.cpr.on&&/before the 30/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('car versus tree: into the car before size-up, costs 10, and she is reached',()=>{const a=open('mva',{loss:300,pelvis:false});const S=a.S();const s=S.score;a.$('m-enter').onclick();return {ok:s-S.score===10&&S.m.inside&&/before sizing up/.test(S.incidents.join(' ')),d:`−${s-S.score}`};});
  T('allergic reaction: an unchecked ampule opened costs 5; on Chaos the bad one is found the hard way, costs 10, and a fresh one is needed',()=>{const a=open('ep',{rebound:false});const S=a.S();S.e.assessed=true;a.setM(a.M());S.mission=1;const s=S.score;a.$('e-syr').onclick();const one=s-S.score===5&&S.e.syr;
    const b=open('ep',{rebound:false},2);const U=b.S();U.e.assessed=true;b.setM(b.M());U.mission=1;const u=U.score;b.$('e-syr').onclick();return {ok:one&&u-U.score===10&&!U.e.syr&&U.e.ampChecked&&U.e.ampBad,d:`good −${s-S.score}, bad −${u-U.score}`};});
};
